# 1. 요약 (Summary)
변경된 주요 내용과 목적을 간단히 요약해주세요.

예시:
- 주문 결제 API의 예외처리 로직 추가 및 로깅 개선


# 2. 작업 내용 (Details)
- 주요 구현 사항 또는 변경점
- 관련된 이슈나 참고 링크 (예: #42)

예시:
- 주문 결제 실패 시 예외를 PaymentException으로 래핑
- 주문 상태 업데이트 트랜잭션 분리
- 결제 로그 수집 시 사용자 ID 추가


# 3. 변경 유형 (Change Type)
해당하는 유형을 선택하여 한 줄로 작성해주세요.

- NEW FEATURE : 새로운 기능 추가
- FIX : 버그 수정
- REFACTOR : 코드 리팩토링
- DOCS : 문서 수정
- PERFORMANCE : 성능 개선
- CHORE : 빌드, 설정, 의존성 변경
- BREAKING CHANGE : 기존 기능에 영향을 주는 변경


# 4. 테스트 방법 (Testing)
PR 검증을 위해 수행한 테스트 내용을 작성해주세요.

예시:
- 주문 생성 → 결제 실패 케이스에서 예외 응답 확인
- 로컬 환경에서 주문 내역 API 호출 시 로그 정상 기록 확인


# 5. 참고 자료 (References)
필요한 경우 캡처 이미지, 로그, 또는 관련 문서를 첨부해주세요.

예시:
- Issue: #42
- Related PR: #17
