name: 리팩토링 이슈 템플릿
about: 코드 구조 개선이나 품질 향상 작업을 위한 템플릿
title: '[Refactor] '
labels: refactor
assignees: ''

---

# 1. 리팩토링 목적 (Goal)
리팩토링의 필요성과 개선 의도를 설명해주세요.

예시:
- PaymentService의 결제 로직 복잡도 감소
- Controller 레벨에서의 중복 응답 코드 제거


# 2. 개선 대상 (Target)
리팩토링할 클래스, 메서드, 패키지 등의 범위를 명시해주세요.


# 3. 개선 방향 (Approach)
적용할 리팩토링 전략이나 패턴을 간략히 기술해주세요.

예시:
- Strategy 패턴 적용
- 메서드 분리 및 의존성 주입 변경


# 4. 테스트 검증 (Testing)
리팩토링 후 영향을 검증할 테스트 항목을 작성해주세요.

예시:
- 기존 단위 테스트 모두 통과 확인
- 성능 측정 결과 비교


# 5. 참고 자료 (References)
- 관련 PR 또는 설계 문서:
